services:
  vulnerabilityscanner.ui:
    image: ${DOCKER_REGISTRY-}vulnerabilityscannerapiui
    build:
      context: ./DetectorVulnerabilitatsUI/DetectorVulnerabilitatsUI # Context dins la carpeta
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - vulnerabilityscanner.api

  vulnerabilityscanner.api:
    image: ${DOCKER_REGISTRY-}vulnerabilityscannerapi
    build:
      context: .
      dockerfile: DetectorVulnerabilitats/Dockerfile
    ports:
        - "8080:8080"
    depends_on:
      - rabbitmq
      - db
      - ollama-puller 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ__HOST=rabbitmq

  vulnerabilityscanner.worker:
    image: ${DOCKER_REGISTRY-}vulnerabilityscannerworker
    build:
      context: .
      dockerfile: Worker/Dockerfile
    ports:
        - "8081:8080"
    depends_on:
      - rabbitmq
      - db
      - ollama-puller 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ__HOST=rabbitmq
      - OllamaUrl=http://ollama-service:11434

  vulnerabilityscanner.worker2:
    image: ${DOCKER_REGISTRY-}vulnerabilityscannerworker
    build:
      context: .
      dockerfile: Worker/Dockerfile
    ports:
        - "8082:8080"
    depends_on:
      - rabbitmq
      - db
      - ollama-puller 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ__HOST=rabbitmq
      - OllamaUrl=http://ollama-service:11434

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Port AMQP
      - "15672:15672"    # UI de gestió
      
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: DetectorVulnerabilitats
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ollama-service:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434" # Opcional, per si vols provar-ho des del navegador del PC
    volumes:
      - ollama_data:/root/.ollama # Important: Persistència dels models baixats
    restart: always

  ollama-puller:
    image: ollama/ollama:latest # Usem la mateixa imatge perquè ja té el client CLI
    container_name: ollama-puller
    depends_on:
      - ollama-service
    volumes:
      - ollama_data:/root/.ollama # Compartim volum per no baixar-ho 2 cops
    entrypoint: /bin/sh
    # La comanda: espera que el servidor arrenqui i després fa el pull
    command: "-c 'sleep 5; ollama pull llama3.2:3b'"
    environment:
      - OLLAMA_HOST=ollama-service:11434 # Li diem on és el servidor

volumes:
  pgdata:
  ollama_data: